name: Addressable
---
Geocodable:
  geocoder: OSMGeocoding

GoogleGeocoding:
  api_url: 'https://maps.googleapis.com/maps/api/geocode/xml'
  api_key: ''

OSMGeocoding:
  api_url: 'http://nominatim.openstreetmap.org/search'
  api_key: ''
